### ISSUE TITLE
Interest in ShareYourCloning / pydna

### ISSUE THREAD

**Issue by manulera** [Lelp27/Lelp27#1]
Hi @sanekun I hope you are doing well. I saw that you recently starred the ShareYourCloning repository. I am looking for users and contributors so if you have any ideas from the user or developer side, feel free to create issues or contact me over email (in my GitHub profile). We can also just have an informal chat!

By the way, if you are looking to contribute to other Open Source projects related to cloning, we are organising a Hackathon about pydna (the python library for cloning that ShareYourCloning uses). You can check it out:

https://github.com/BjornFJohansson/pydna/discussions/258

Best,
Manu

**Comment by sanekun** [comment]
Thanks for sharing and introduce ShareYourCloning and pydna project @manulera .
I already use and track pydna project also.
The code-based cloning system is really important for recent synthetic biology task.
So I'm trying to make some API can parse DNA data and calculate certain properties for machine behavior.

However, I am still considering how should I organize a format for utilizing them and which function exactly I need.
I hope I can contribute when I have some ideas or my work is organized. For that I will keep watching these project ever.

Regard,
Kun

**Comment by manulera** [comment]
Hey Kun, thanks for the followup. Feel free to join the hackathon for contributing / discussing.

The date will be announced soon in the discussion!
